version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./mysql:/var/lib/mysql
     ports:
      - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: wpdocker
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     volumes:
       - "./wordpress:/var/www/html"
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress

   pma:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - 8080:80
     environment:
       PMA_HOST: db:3306
       MYSQL_ROOT_PASSWORD: wpdocker

volumes:
    mysql: